# Análise do Desempenho Comercial – Olist (2017–2018)

##1 Objetivo do Projeto

O objetivo desta análise é compreender o desempenho comercial de um e-commerce no período entre 2017 e agosto de 2018, avaliando a evolução do volume de pedidos, da receita e do comportamento de consumo dos clientes.

## Pergunta Norteadora

Como evoluiu o desempenho comercial do e-commerce entre 2017 e 2018 e o que essa evolução indica sobre o crescimento do negócio e a geração de receita?

## 2 Base de Dados

Foram utilizados diferentes conjuntos de dados da Olist, incluindo informações sobre clientes, pedidos, pagamentos, produtos e categorias.

Esses dados permitiram analisar o comportamento de compra, a distribuição geográfica da demanda e o desempenho dos produtos ao longo do tempo.

In [297]:
# Carregamento dos dados
import pandas as pd

# Base de clientes
df_customers = pd.read_csv('/content/olist_customers_dataset.csv')

# Itens dos pedidos
df_orderitems = pd.read_csv('/content/olist_order_items_dataset.csv')

# Pagamentos dos pedidos
df_orderpayments = pd.read_csv('/content/olist_order_payments_dataset.csv')

# Pedidos
df_orders = pd.read_csv('/content/olist_orders_dataset.csv')

# Produtos
df_products = pd.read_csv('/content/olist_products_dataset.csv')

# Tradução das categorias de produtos
df_product_categoryen = pd.read_csv('/content/product_category_name_translation.csv')

## 3 Exploratory Data Analysis (EDA)

A etapa de análise exploratória teve como objetivo compreender a estrutura dos dados, identificar possíveis inconsistências e avaliar a qualidade das informações disponíveis.

Foram realizadas análises de valores nulos, duplicados e distribuição das variáveis principais, como localização dos clientes, status dos pedidos e características dos produtos.

Observou-se uma forte concentração de clientes na região Sudeste, especialmente no estado de São Paulo, indicando sua relevância no mercado de e-commerce brasileiro.

# 3.1 Customers

In [224]:
# Análise exploratória dos dados de clientes (EDA)

# Visualização inicial dos dados
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [225]:
# Estrutura e tipos de dados do dataset
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [226]:
# Verificação de valores nulos
df_customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [227]:
# Verificação de registros duplicados
df_customers.duplicated().sum()

np.int64(0)

In [228]:
# Análise de qualidade dos dados de clientes

# customer_id representa o identificador do pedido
# customer_unique_id representa o cliente único

# Verificação de valores nulos por coluna
display(df_customers.isnull().sum())

# Verificação de registros duplicados
print("Duplicados:", df_customers.duplicated().sum())

# Quantidade de pedidos únicos
print("Customer ID únicos:", df_customers["customer_id"].nunique())

# Quantidade de clientes únicos
print("Customer Unique ID únicos:", df_customers["customer_unique_id"].nunique())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicados: 0
Customer ID únicos: 99441
Customer Unique ID únicos: 96096

In [229]:
# Análise da distribuição geográfica dos clientes

# Frequência de clientes por estado
df_customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [230]:
# Distribuição percentual de clientes por estado
df_customers["customer_state"].value_counts(normalize=True)

# Observa-se uma forte concentração de clientes na região Sudeste,
# especialmente no estado de São Paulo, que se destaca como o principal mercado consumidor,
# influenciado pela maior densidade populacional e maior presença de e-commerce.

customer_state
SP    0.419807
RJ    0.129242
MG    0.117004
RS    0.054967
PR    0.050734
SC    0.036574
BA    0.033990
DF    0.021520
ES    0.020444
GO    0.020314
PE    0.016613
CE    0.013435
PA    0.009805
MT    0.009121
MA    0.007512
MS    0.007190
PB    0.005390
PI    0.004978
RN    0.004877
AL    0.004153
SE    0.003520
TO    0.002816
RO    0.002544
AM    0.001488
AC    0.000815
AP    0.000684
RR    0.000463
Name: proportion, dtype: float64

## 3.2 Orders

In [231]:
# Análise exploratória dos dados de pedidos (EDA)

# Visualização inicial dos dados
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [232]:
# Estrutura e tipos de dados do dataset de pedidos
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [233]:
# Análise de qualidade dos dados de pedidos

# Verificação de valores nulos por coluna
display(df_orders.isnull().sum())

# Verificação de registros duplicados
print("Duplicados:", df_orders.duplicated().sum())

# Quantidade de pedidos único
print("Order ID únicos:", df_orders["order_id"].nunique())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicados: 0
Order ID únicos: 99441

In [234]:
# Distribuição do status dos pedidos
df_orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

## 3.3 Payments

In [235]:
# Análise exploratória dos dados de pagamentos (EDA)

# Visualização inicial dos dados
df_orderpayments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [236]:
# Estrutura e tipos de dados do dataset de pagamentos

df_orderpayments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [237]:
# Análise de qualidade dos dados de pagamentos

display(df_orderpayments.isnull().sum())

print("Duplicados:",df_orderpayments.duplicated().sum())

print("Order ID únicos:", df_orderpayments["order_id"].nunique())

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicados: 0
Order ID únicos: 99440

## 3.4 Order Items

In [238]:
# Análise exploratória dos itens de pedidos (EDA)

# Visualização inicial dos dados
display(df_orderitems.head())

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [239]:
# Estrutura e tipos de dados do dataset de itens de pedidos

df_orderitems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [240]:
# Análise de qualidade dos dados de itens de pedidos
display(df_orderitems.isnull().sum())

print("Duplicados:", df_orderitems.duplicated().sum())

print("Order ID únicos:", df_orderitems["order_id"].nunique())

# Observa-se que existem 112.650 itens vendidos para 98.666 pedidos,
# indicando que há pedidos com múltiplos itens.

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicados: 0
Order ID únicos: 98666

In [241]:
# Identificação dos produtos mais vendidos
df_orderitems["product_id"].value_counts().head(10)

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
Name: count, dtype: int64

##3.5 Products

In [242]:
# Análise exploratória dos dados de produtos (EDA)

# Visualização inicial dos dados
display(df_products.head())

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [243]:
# Estrutura e tipos de dados do dataset de produtos
df_products.info()

# Observa-se a existência de produtos sem classificação de categoria (product_category_name)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [244]:
# Análise de qualidade dos dados de produtos

# Verificação de valores nulos por coluna
display(df_products.isnull().sum())

# Verificação de registros duplicados
print("Duplicados:", df_products.duplicated().sum())

# Quantidade de produtos únicos
print("Product ID únicos:", df_products["product_id"].nunique())

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicados: 0
Product ID únicos: 32951

In [245]:
# Identificação das principais categorias de produtos (Top 10)
df_products["product_category_name"].value_counts().head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

##3.5 Category Translation

In [246]:
# Análise exploratória da tabela de tradução de categorias (EDA)

# Visualização inicial dos dados
df_product_categoryen.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [247]:
# Estrutura dos dados da tabela de tradução de categorias
df_product_categoryen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [248]:
# Análise de qualidade dos dados da tabela de tradução de categorias

# Verificação de valores nulos por coluna
display(df_product_categoryen.isnull().sum())

# Verificação de registros duplicados
print("Duplicados:", df_product_categoryen.duplicated().sum())

# Quantidade de categorias únicas
print("Categorias únicas:", df_product_categoryen["product_category_name"].nunique())

product_category_name            0
product_category_name_english    0
dtype: int64

Duplicados: 0
Categorias únicas: 71

##4 Data Cleaning

## Tratamento de Dados

Nesta etapa, foram realizadas transformações importantes para garantir a consistência dos dados, incluindo:

- Conversão de colunas de data para o formato adequado
- Padronização de nomes de colunas
- Validação de duplicidades e valores nulos

Esses ajustes foram essenciais para garantir a confiabilidade das análises posteriores.

##4.1 Converter datas (ORDERS)

In [249]:
# Conversão das colunas de data da tabela de pedidos para o formato datetime
df_orders["order_purchase_timestamp"] = pd.to_datetime(df_orders["order_purchase_timestamp"])
df_orders["order_approved_at"] = pd.to_datetime(df_orders["order_approved_at"])
df_orders["order_delivered_carrier_date"]= pd.to_datetime(df_orders["order_delivered_carrier_date"])
df_orders["order_delivered_customer_date"] = pd.to_datetime(df_orders["order_delivered_customer_date"])
df_orders["order_estimated_delivery_date"] = pd.to_datetime(df_orders["order_estimated_delivery_date"])

print(df_orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB
None

##4.2 Padronizar nomes- Customers e Products

In [250]:
# Padronização dos nomes das colunas da tabela de clientes
df_customers = df_customers.rename(columns={
     "customer_city": "city",
     "customer_state": "state"
})

In [251]:
# Padronização dos nomes das colunas da tabela de produtos
df_products = df_products.rename(columns={
    "product_category_name": "category"
    })

##5 Construção do Dataset 1 (Pedidos)

O Dataset 1 foi estruturado com o objetivo de analisar o desempenho do negócio em nível de pedido.

Para isso, foram integradas as tabelas de pedidos, pagamentos e clientes, permitindo consolidar informações de receita e localização geográfica em uma única base.

Esse dataset foi utilizado principalmente na análise de crescimento e receita (KPI 1).

In [252]:
# Estrutura do Dataset 1: integração das tabelas de pedidos, pagamentos e clientes
df_payments_agg = df_orderpayments.groupby("order_id")["payment_value"].sum().reset_index()

# A tabela de pagamentos possui múltiplas linhas por pedido,
# sendo necessário realizar a agregação para consolidar a receita por pedido

# Transformação: conversão de múltiplas linhas por pedido em uma única linha por pedido

In [253]:
# Join 1 orders + payments

df_orders_payments = df_orders.merge(df_payments_agg, on="order_id", how="left")

In [254]:
# Join 2 + customers

df_dataset1 = df_orders_payments_customers = df_orders_payments.merge(df_customers, on="customer_id" , how="left")

In [255]:
df_dataset1.shape

(99441, 13)

In [256]:
df_dataset1.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_value,customer_unique_id,customer_zip_code_prefix,city,state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,38.71,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,141.46,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,179.12,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,72.20,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,28.62,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [257]:
df_dataset1["order_id"].nunique()

99441

In [258]:
df_orders["order_id"].nunique()

99441

In [259]:
df_dataset1.duplicated().sum()

np.int64(0)

In [260]:
df_dataset1["payment_value"].sum()

np.float64(16008872.120000001)

In [261]:
df_orderpayments["payment_value"].sum()

np.float64(16008872.12)

In [262]:
df_dataset1.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
payment_value                       1
customer_unique_id                  0
customer_zip_code_prefix            0
city                                0
state                               0
dtype: int64

##5.1 Construção do Dataset 2 (Itens e Produtos)

O Dataset 2 foi estruturado em nível de item, permitindo uma análise mais detalhada dos produtos.

Foram integradas informações de itens de pedido, produtos, categorias, pedidos e clientes, possibilitando avaliar o desempenho por categoria, volume de vendas e geração de receita.

Esse dataset foi utilizado principalmente nas análises de categorias e produtos (KPI 2 e KPI 3).

##5.2 Join 1, 2, 3 e 4 DATASET2 - ITENS/PRODUTOS

In [263]:
# # Join 1: integração entre itens de pedidos e produtos
df_items_products = df_orderitems.merge(
    df_products,
    on="product_id",
    how="left"
)

# Permite associar cada item vendido às informações do produto,
# como categoria, descrição e características físicas

# Objetivo:
# - Analisar os produtos vendidos
# - Compreender as características dos produtos
# - Preparar a base para análise por categoria

In [264]:
df_items_products.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'category',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm'],
      dtype='object')

In [265]:
# Join 2: integração com a tabela de tradução de categorias
# Permite traduzir os nomes das categorias para inglês, garantindo a padronização dos dados

# Objetivo:
# - Melhorar a visualização das categorias
# - Padronizar a análise
# - Facilitar o uso dos dados no Power BI

df_items_products = df_items_products.merge(
    df_product_categoryen,
    left_on="category",
    right_on= "product_category_name",
    how="left"
)

In [266]:
df_items_products.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,category,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,cool_stuff,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,pet_shop,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,moveis_decoracao,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,perfumaria,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,ferramentas_jardim,garden_tools

In [267]:
# Ajuste das colunas após integração das tabelas

# Remoção de colunas duplicadas (quando necessário)
# df_items_products = df_items_products.drop(columns=["product_category_name"])

# Padronização dos nomes das colunas de categoria (português e inglês)

df_items_products = df_items_products.rename(columns={
    "category": "category_pt",
    "product_category_name_english": "category_en"
})

In [268]:
# Reorganização da posição da coluna de categoria em inglês

df_items_products.insert(
    8,
    "category_en",
    df_items_products.pop("category_en")
)

In [269]:
df_items_products.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'category_pt',
       'category_en', 'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'product_category_name'],
      dtype='object')

In [270]:
# Join 3: integração com a tabela de pedidos

# Adiciona informações temporais e status do pedido,
# permitindo análises ao longo do tempo

# Objetivo:
# - Analisar o comportamento de compra ao longo do tempo
# - Avaliar produtos por período
# - Incorporar o status dos pedidos na análise

df_items_products = df_items_products.merge(
    df_orders,
    on="order_id",
    how="left"
)

In [271]:
# Join 4: integração com a tabela de clientes

# Merge: operação de união entre tabelas
# on: coluna utilizada como chave de ligação
# how="left": mantém todos os registros da tabela principal

df_dataset2 = df_items_products.merge(
    df_customers,
    on = "customer_id",
    how = "left"
)

In [272]:
df_dataset2.shape

(112650, 28)

In [273]:
df_dataset2.duplicated().sum()

np.int64(0)

In [274]:
df_dataset1.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
payment_value                       1
customer_unique_id                  0
customer_zip_code_prefix            0
city                                0
state                               0
dtype: int64

##6 KPIs

##6.1 KPI 3 Categorias e Produtos

A análise comparativa entre volume de vendas e receita evidenciou diferenças importantes entre as categorias.

Enquanto categorias como Cama, Mesa e Banho apresentam maior volume de vendas, Beleza & Saúde se destaca na geração de receita.

Esse comportamento indica que o desempenho financeiro não depende apenas da quantidade vendida, mas também do valor agregado dos produtos.

In [275]:
df_dataset2.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'category_pt',
       'category_en', 'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'product_category_name',
       'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'city', 'state'],
      dtype='object')

In [276]:
df_dataset2["product_description_lenght"]

0          598.0
1          239.0
2          695.0
3          480.0
4          409.0
           ...
112645    1002.0
112646     232.0
112647     869.0
112648    1306.0
112649     511.0
Name: product_description_lenght, Length: 112650, dtype: float64

In [277]:
# Cálculo da receita total em nível de item, utilizado para validação com o KPI 1
df_dataset2["price"].sum()

np.float64(13591643.700000003)

In [278]:
# Identificação dos produtos com maior volume de vendas

top_qtd = (
    df_dataset2
    .groupby(["product_id",
             "category_pt",
             "category_en"
    ])
    .agg(qtd_vendida=("order_item_id", "count"))
    .sort_values(by="qtd_vendida", ascending=False)
    .head(5)
)

top_qtd

                                                                     qtd_vendida
product_id                       category_pt        category_en
aca2eb7d00ea1a7b8ebd4e68314663af moveis_decoracao   furniture_decor          527
99a4788cb24856965c36a24e339b6058 cama_mesa_banho    bed_bath_table           488
422879e10f46682990de24d770e7f83d ferramentas_jardim garden_tools             484
389d119b48cf3043d311335e499d9c6b ferramentas_jardim garden_tools             392
368c6c730842d78016ad823897a372db ferramentas_jardim garden_tools             388

In [279]:
# Identificação dos produtos com maior geração de receita

top_receita = (
    df_dataset2
    .groupby(["product_id",
              "category_pt",
             "category_en"])
    .agg(receita=("price","sum"))
    .sort_values(by="receita", ascending=False)
    .head(5)
)

top_receita

                                                                                receita
product_id                       category_pt            category_en
bb50f2e236e5eea0100680137654686c beleza_saude           health_beauty          63885.00
6cdd53843498f92890544667809f1595 beleza_saude           health_beauty          54730.20
d6160fb7873f184099d9bc95e30376af pcs                    computers              48899.34
d1c427060a0f73f6b889a5c7c61f2ac4 informatica_acessorios computers_accessories  47214.51
99a4788cb24856965c36a24e339b6058 cama_mesa_banho        bed_bath_table         43025.56

In [280]:
# Identificação dos 5 produtos com maior geração de receita

# Métricas consideradas:
# - Receita total por produto
# - Quantidade vendida

# Objetivo:
# Identificar os produtos com maior impacto financeiro no e-commerce,
# considerando simultaneamente receita e volume de vendas

top_produtos = (
    df_dataset2
    .groupby(["product_id", "category_pt", "category_en"])
    .agg(
        receita=("price", "sum"),
        qtd_vendida=("order_item_id", "count")
    )
    .sort_values(by="receita", ascending=False)
    .head(5)
)

top_produtos

,,,receita,qtd_vendida
product_id,category_pt,category_en,,
bb50f2e236e5eea0100680137654686c,beleza_saude,health_beauty,63885.00,195
6cdd53843498f92890544667809f1595,beleza_saude,health_beauty,54730.20,156
d6160fb7873f184099d9bc95e30376af,pcs,computers,48899.34,35
d1c427060a0f73f6b889a5c7c61f2ac4,informatica_acessorios,computers_accessories,47214.51,343
99a4788cb24856965c36a24e339b6058,cama_mesa_banho,bed_bath_table,43025.56,488

##6.2 KPI 1 Crescimento e Receita

A análise do KPI 1 permitiu avaliar a evolução do volume de pedidos e da receita ao longo do tempo.

Observou-se um crescimento consistente ao longo de 2017, seguido por uma estabilização em 2018. O ticket médio manteve-se relativamente estável, indicando que o crescimento do negócio foi impulsionado principalmente pelo aumento no volume de pedidos.

In [281]:
# Cálculo da receita total do e-commerce

receita_total = df_dataset1["payment_value"].sum()
receita_total

np.float64(16008872.120000001)

In [282]:
# Análise da evolução da receita ao longo do tempo (criação da variável de período mensal)
df_dataset1["ano_mes"] = df_dataset1["order_purchase_timestamp"].dt.to_period("M")

In [283]:
# Agregação da receita por mês
receita_mensal = (
    df_dataset1
    .groupby("ano_mes")
    .agg(receita=("payment_value", "sum"))
    .reset_index()
    .sort_values("ano_mes")
)

receita_mensal

    ano_mes     receita
0   2016-09      252.24
1   2016-10    59090.48
2   2016-12       19.62
3   2017-01   138488.04
4   2017-02   291908.01
5   2017-03   449863.60
6   2017-04   417788.03
7   2017-05   592918.82
8   2017-06   511276.38
9   2017-07   592382.92
10  2017-08   674396.32
11  2017-09   727762.45
12  2017-10   779677.88
13  2017-11  1194882.80
14  2017-12   878401.48
15  2018-01  1115004.18
16  2018-02   992463.34
17  2018-03  1159652.12
18  2018-04  1160785.48
19  2018-05  1153982.15
20  2018-06  1023880.50
21  2018-07  1066540.75
22  2018-08  1022425.32
23  2018-09     4439.54
24  2018-10      589.67

In [284]:
# Identificação de inconsistências em alguns períodos,
# sendo necessária a validação da quantidade de pedidos ao longo do tempo

# Quantidade de pedidos por mês

df_dataset1.groupby("ano_mes")["order_id"].count()

ano_mes
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
2017-03    2682
2017-04    2404
2017-05    3700
2017-06    3245
2017-07    4026
2017-08    4331
2017-09    4285
2017-10    4631
2017-11    7544
2017-12    5673
2018-01    7269
2018-02    6728
2018-03    7211
2018-04    6939
2018-05    6873
2018-06    6167
2018-07    6292
2018-08    6512
2018-09      16
2018-10       4
Freq: M, Name: order_id, dtype: int64

In [285]:
# Filtragem do período relevante para análise
df_filtrado = df_dataset1[
    (df_dataset1["order_purchase_timestamp"] >= "2017-01-01") &
    (df_dataset1["order_purchase_timestamp"] <= "2018-08-31")
]

In [286]:
# Ajuste do formato de data para visualização em gráfico

# Conversão do período mensal para formato de data completa,
# permitindo melhor representação no eixo temporal

# Utiliza-se to_period() para agregação mensal
# e to_timestamp() para conversão em formato adequado para visualização

receita_mensal["ano_mes"] = receita_mensal["ano_mes"].dt.to_timestamp()

##6.3 KPI 2 Distribuição da Receita

A análise da distribuição da receita permitiu identificar as principais regiões e categorias responsáveis pelo desempenho do negócio.

Observou-se uma forte concentração da receita no estado de São Paulo, seguido por Rio de Janeiro e Minas Gerais. Em relação às categorias, Beleza & Saúde destacou-se como a principal fonte de receita.

Esses resultados evidenciam a importância da distribuição geográfica e do mix de produtos na geração de receita.

In [287]:
# Análise da receita por categoria de produtos

receita_categoria = (
    df_dataset2
    .groupby("category_en")
    .agg(receita=("price", "sum"))
    .sort_values(by="receita", ascending=False)
    .reset_index()
)

receita_categoria

                  category_en     receita
0               health_beauty  1258681.34
1               watches_gifts  1205005.68
2              bed_bath_table  1036988.68
3              sports_leisure   988048.97
4       computers_accessories   911954.32
..                        ...         ...
66                    flowers     1110.04
67             home_comfort_2      760.27
68          cds_dvds_musicals      730.00
69  fashion_childrens_clothes      569.85
70      security_and_services      283.29

[71 rows x 2 columns]

In [288]:
# Análise da participação percentual da receita por categoria

receita_categoria["perc"] = (
    receita_categoria["receita"] /
    receita_categoria["receita"].sum()
) * 100

receita_categoria.head(10)

             category_en     receita      perc
0          health_beauty  1258681.34  9.388524
1          watches_gifts  1205005.68  8.988157
2         bed_bath_table  1036988.68  7.734915
3         sports_leisure   988048.97  7.369873
4  computers_accessories   911954.32  6.802282
5        furniture_decor   729762.49  5.443310
6             cool_stuff   635290.85  4.738645
7             housewares   632248.66  4.715953
8                   auto   592720.11  4.421109
9           garden_tools   485256.46  3.619536

In [289]:
# Análise da receita por estado

receita_estado = (
    df_dataset2
    .groupby("state")
    .agg(receita=("price", "sum"))
    .sort_values(by="receita", ascending=False)
    .reset_index()
)

receita_estado

   state     receita
0     SP  5202955.05
1     RJ  1824092.67
2     MG  1585308.03
3     RS   750304.02
4     PR   683083.76
5     SC   520553.34
6     BA   511349.99
7     DF   302603.94
8     GO   294591.95
9     ES   275037.31
10    PE   262788.03
11    CE   227254.71
12    PA   178947.81
13    MT   156453.53
14    MA   119648.22
15    MS   116812.64
16    PB   115268.08
17    PI    86914.08
18    RN    83034.98
19    AL    80314.81
20    SE    58920.85
21    TO    49621.74
22    RO    46140.64
23    AM    22356.84
24    AC    15982.95
25    AP    13474.30
26    RR     7829.43

In [290]:
# Análise da participação percentual da receita por estado

receita_estado["perc"] = (
    receita_estado["receita"] /
    receita_estado["receita"].sum()
) * 100

receita_estado.head(10)

  state     receita       perc
0    SP  5202955.05  38.280543
1    RJ  1824092.67  13.420692
2    MG  1585308.03  11.663843
3    RS   750304.02   5.520333
4    PR   683083.76   5.025763
5    SC   520553.34   3.829951
6    BA   511349.99   3.762238
7    DF   302603.94   2.226397
8    GO   294591.95   2.167449
9    ES   275037.31   2.023577

##6.4 Continuação KPI 1
Numero de pedidos por mês
Juntar com receita mensal
Ticket médio
Crescimento (VARIAÇÃO)

In [291]:
# Análise do número de pedidos por mês

pedidos_mensal = (
    df_dataset1
    .groupby("ano_mes")
    .agg(pedidos=("order_id", "count"))
    .reset_index()
)

pedidos_mensal

    ano_mes  pedidos
0   2016-09        4
1   2016-10      324
2   2016-12        1
3   2017-01      800
4   2017-02     1780
5   2017-03     2682
6   2017-04     2404
7   2017-05     3700
8   2017-06     3245
9   2017-07     4026
10  2017-08     4331
11  2017-09     4285
12  2017-10     4631
13  2017-11     7544
14  2017-12     5673
15  2018-01     7269
16  2018-02     6728
17  2018-03     7211
18  2018-04     6939
19  2018-05     6873
20  2018-06     6167
21  2018-07     6292
22  2018-08     6512
23  2018-09       16
24  2018-10        4

In [292]:
# Integração do volume de pedidos com a receita mensal

kpi1 = (
    df_dataset1
    .groupby('ano_mes')
    .agg(
        receita=('payment_value', 'sum'),
        pedidos=('order_id', 'count')
    )
    .reset_index()
)

kpi1.head()

   ano_mes    receita  pedidos
0  2016-09     252.24        4
1  2016-10   59090.48      324
2  2016-12      19.62        1
3  2017-01  138488.04      800
4  2017-02  291908.01     1780

In [293]:
# Cálculo do ticket médio

kpi1["ticket_medio"] = kpi1["receita"] / kpi1["pedidos"]

kpi1.head()

   ano_mes    receita  pedidos  ticket_medio
0  2016-09     252.24        4     63.060000
1  2016-10   59090.48      324    182.378025
2  2016-12      19.62        1     19.620000
3  2017-01  138488.04      800    173.110050
4  2017-02  291908.01     1780    163.993264

In [294]:
# Análise da variação da receita ao longo do tempo

#VARIAÇÃO absoluta

kpi1["var_receita_abs"] = kpi1["receita"].diff()

#Variacao percentual

kpi1["var_receita"] = kpi1["receita"].pct_change() * 100

kpi1['var_receita_pct_str'] = kpi1['var_receita'].round(2).astype(str) + '%'
kpi1.head()

kpi1.head()

,ano_mes,receita,pedidos,ticket_medio,var_receita_abs,var_receita,var_receita_pct_str
0,2016-09,252.24,4,63.060000,NaN,NaN,nan%
1,2016-10,59090.48,324,182.378025,58838.24,23326.292420,23326.29%
2,2016-12,19.62,1,19.620000,-59070.86,-99.966797,-99.97%
3,2017-01,138488.04,800,173.110050,138468.42,705751.376147,705751.38%
4,2017-02,291908.01,1780,163.993264,153419.97,110.782108,110.78%

In [295]:
# 1. Filtrar período saudável (COM .copy() para evitar erro)
df_filtrado = df_dataset1[
    (df_dataset1["order_purchase_timestamp"] >= "2017-01-01") &
    (df_dataset1["order_purchase_timestamp"] <= "2018-08-31")
].copy()

# 2. Criar coluna ano_mes
df_filtrado['ano_mes'] = df_filtrado['order_purchase_timestamp'].dt.to_period('M')

# 3. Agrupar (receita + pedidos)
kpi1 = (
    df_filtrado
    .groupby('ano_mes')
    .agg(
        receita=('payment_value', 'sum'),
        pedidos=('order_id', 'count')
    )
    .reset_index()
)

# 4. Ticket médio
kpi1['ticket_medio'] = kpi1['receita'] / kpi1['pedidos']

# 5. Variação absoluta
kpi1['var_receita_abs'] = kpi1['receita'].diff()

# 6. Variação percentual (%)
kpi1['var_receita'] = kpi1['receita'].pct_change() * 100

# 7. Remover primeira linha (não tem comparação)
kpi1 = kpi1.iloc[1:]

# 8. Arredondar para 2 casas
kpi1 = kpi1.round(2)

# 9. Converter data para formato de gráfico
kpi1['ano_mes'] = kpi1['ano_mes'].dt.to_timestamp()

# 10. Mostrar resultado
kpi1.head()

     ano_mes    receita  pedidos  ticket_medio  var_receita_abs  var_receita
1 2017-02-01  291908.01     1780        163.99        153419.97       110.78
2 2017-03-01  449863.60     2682        167.73        157955.59        54.11
3 2017-04-01  417788.03     2404        173.79        -32075.57        -7.13
4 2017-05-01  592918.82     3700        160.25        175130.79        41.92
5 2017-06-01  511276.38     3245        157.56        -81642.44       -13.77

##7 Exportar dados do Python

In [296]:
# Exportação dos datasets para utilização no Power BI

df_dataset1.to_csv("dataset1.csv", index=False)
df_dataset2.to_csv("dataset2.csv", index=False)

## Conclusão

A análise do desempenho comercial do Olist evidencia que o crescimento do negócio está diretamente associado ao aumento no volume de pedidos, mantendo um ticket médio relativamente estável.

Além disso, a concentração da receita em determinadas regiões e categorias reforça a importância de estratégias focadas em mercado e portfólio de produtos.

De forma geral, os resultados demonstram que o crescimento sustentável do e-commerce depende não apenas da expansão das vendas, mas também da eficiência na geração de valor.